### ISSUE TITLE
Login_error

### ISSUE THREAD

**Issue by Heki2017** [abaretta/nu.baretta.winddelen#1]
Hi Anne, I recently wanted to add a windmill but found that I got a login error in Homey when adding the mill. I decided to download the (new) beta version. But it gave me the same error code. Do you know what is going on?

**Comment by abaretta** [comment]
No idea, the data is publicly available without any authentication or login? Can you describe what you attempted to do in some more detail?

Thanks,

Regards, Anne

**Comment by Heki2017** [comment]
Hi Anne, I installed the beta app (after the former version did not update the windmills) and when I wanted to create new devices I got this screen:


Hope this helps, kind regards Hedzer
