### ISSUE TITLE
http not supported anymore

### ISSUE THREAD

**Issue by dhover** [abaretta/nu.baretta.winddelen#2]
Adding Winddelen device to Homey produces an "login_error" error.
The url baseurl1 is now http. http is not supported anymore. Please change to https.

**Comment by abaretta** [comment]
I just noticed this. Http is supported but the URL has changed. I have updated the app, should be updated in the app store shortly.

**Comment by dhover** [comment]
Dear Anne,

There is still an error in baseurl1. The protocol has to be https!

Dinant

Op 22 jan. 2018 12:57 schreef "abaretta" <notifications@github.com>:

I just noticed this. Http is supported but the URL has changed. I have
updated the app, should be updated in the app store shortly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abaretta/nu.baretta.winddelen/issues/2#issuecomment-359402948>,
or mute the thread
