### ISSUE TITLE
Homey Energy

### ISSUE THREAD

**Issue by FooWorks** [abaretta/nu.baretta.winddelen#5]
the current implementation could perhaps work nicer in the Homey Energy Tab. By imitating Solar Panels the production would be shown as actual production. 

As far as I see the /app.json should use the "class": "solarpanel" and the production should be in positive numbers.

https://developer.athom.com/docs/apps/tutorial-Drivers-Energy.html

**Comment by abaretta** [comment]
Good suggestion! I have fixed it, thanks. Waiting for the appstore to publish the update...

**Comment by abaretta** [comment]
Ah, hang on, it works, but it requires repairing because of the changed capabilities :-/
